- alias: "Update Available Notification"
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.all
    data_template:
      title: "Home Assistant Update"
      message: {"event":"device_status", "value1":"Home Assistant Update: ", "value2":"Available"}
      data:
          icon: "https://goo.gl/xeetdy"
