homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  #latitude: !secret home_latitude
  #longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  #elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  #time_zone: !secret home_time_zone
  customize: !include customize.yaml

  #packages:
    #homeassistant: !include packages/homeassistant.yaml
    #ipaddress: !include packages/ipaddress.yaml
    #datetime: !include packages/datetime.yaml
    #mqtt: !include packages/mqtt.yaml
    #sip_call: !include packages/sip_call.yaml
    #presence: !include packages/presence.yaml
    #geo: !include packages/geo.yaml
    #security: !include packages/security.yaml
    #climate: !include packages/climate.yaml
    #power: !include packages/power.yaml
    #cameras: !include packages/cameras.yaml
    #weather: !include packages/weather.yaml
    #workingdays: !include packages/workingdays.yaml
    #calendars: !include packages/calendars.yaml
    #mediaplayer: !include packages/mediaplayer.yaml
    #squeezebox_alert: !include packages/squeezebox_alert.yaml
    #kids: !include packages/kids.yaml
    #fitness: !include packages/fitness.yaml
    #floorplan: !include packages/floorplan.yaml
    #delivery_tracking: !include packages/delivery_tracking.yaml
    #vehicules: !include packages/vehicules.yaml
    #crime: !include packages/crime.yaml
    #pihole: !include packages/pihole.yaml
    #uber: !include packages/uber.yaml
    #haveibeenpwned: !include packages/haveibeenpwned.yaml
    #away: !include packages/away.yaml

http:
  #api_password: !secret http_api_password

# Enables the frontend
frontend:
  #themes: !include packages/themes.yaml

config:

# Enable sun tracking
sun:

zwave:
  usb_path: /dev/ttyACM0
  network_key: "0x26, 0x66, 0x54, 0xE0, 0xBB, 0x30, 0xCA, 0x48, 0x0E, 0xE3, 0xA3, 0x52, 0xFB, 0x33, 0x14, 0xC0"

# zone 1:
#   name: Home
#   latitude: !secret home_latitude
#   longitude: !secret home_longitude
#   radius: 300
#   icon: mdi:home

# zone 2:
#   name: Innovapost
#   latitude: !secret innovapost_latitude
#   longitude: !secret innovapost_longitude
#   radius: 300
#   icon: mdi:email

# zone 3:
#   name: Nav Canada
#   latitude: !secret navcanada_latitude
#   longitude: !secret navcanada_longitude
#   radius: 300
#   icon: mdi:office-building

# zone 4:
#   name: Nav Canada TSC
#   latitude: !secret navcanadatsc_latitude
#   longitude: !secret navcanadatsc_longitude
#   radius: 300
#   icon: mdi:airport

# zone 5:
#   name: Fitness Lab
#   latitude: !secret fitness_lab_latitude
#   longitude: !secret fitness_lab_longitue
#   radius: 300
#   icon: mdi:run-fast

# Discover some devices automatically
discovery:

# Enables notifications
notify:
  # - platform: joaoapps_join
  #   api_key: !secret join_api_key
  #   device_id: !secret join_device_id
  #   device_ids: !secret join_device_ids
  #   device_names: ZUK Z1
  #   name: join

  - name: all
    platform: group
    services:
      # - service: join
      - service: notify

# joaoapps_join:
#   - name: android
#     device_id: group.android
#     api_key: !secret join_api_key

recorder:
  purge_interval: 1
  purge_keep_days: 31

logger:
  default: notset

group: !include group.yaml

automation: !include automation.yaml

zeroconf:

ios:

map:

cloud:
  alexa:
    filter:
      exclude_domains:
        - script
        - automation
        - group
