homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret homeassistant_time_zone
  customize: !include customize.yaml

  # Packages
  packages:
    homeassistant: !include packages/homeassistant.yaml
    ipaddress: !include packages/ipaddress.yaml
    datetime: !include packages/datetime.yaml
    mqtt: !include packages/mqtt.yaml
    sip_call: !include packages/sip_call.yaml
    presence: !include packages/presence.yaml
    geo: !include packages/geo.yaml
    security: !include packages/security.yaml
    climate: !include packages/climate.yaml
    power: !include packages/power.yaml
    cameras: !include packages/cameras.yaml
    weather: !include packages/weather.yaml
    workingdays: !include packages/workingdays.yaml
    calendars: !include packages/calendars.yaml
    mediaplayer: !include packages/mediaplayer.yaml
    squeezebox_alert: !include packages/squeezebox_alert.yaml
    kids: !include packages/kids.yaml

http:
  #base_url: 192.168.101.12:8123
  api_password: !secret http_api_password
#  ssl_certificate: /config/fullchain.pem
#  ssl_key: /config/privkey.pem
  #use_x_forwarded_for: True
  #trusted_networks:
  #  - 127.0.0.1
  #  - ::1
  #  - 192.168.101.0/24

# Enables the frontend
frontend:
# Enables the configration UI
config:
# Enable sun tracking
sun:

zone 1:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  radius: 300
  icon: mdi:home

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date

# Enables notifications
notify:
  - name: pushbullet_notify
    platform: pushbullet
    api_key: !secret pushbullet_api_key

recorder:
  purge_days: 21

weblink:
  entities:
    - name: Router
      url: https://192.168.101.1
    - name: Rancher
      url: http://192.168.101.12:8080
    - name: Logitech Squeezebox Server
      url: http://192.168.101.12:9000
    - name: ZoneMinder
      url: http://192.168.101.12:8083/zm
    - name: Alarm Keypad
      url: https://192.168.101.17/keypad/

# View all events in a logbook
logbook:

#  - platform: torque
#    email: !secret torque_email
sensor:
  - platform: template
    sensors:
      marty_battery:
        value_template: '{{ states.device_tracker.martyszuk1_z1.attributes.battery }}'
        friendly_name: Marty's Phone Battery
        unit_of_measurement: '%'
  - platform: ups
    name: ups_deliveries
    username: retro_hunter
    password: !secret ups_password

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

tts:
  - platform: google
    language: 'en'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
  #- platform: yandextts
    #api_key: !secret yandextts_api_key
    #codec: wav
    #voice: oksana
    #emotion: evil
    #speed: 2
  #- platform: picotts
  #platform: voicerss
  #api_key: !secret voicerss_api_key

#input_select:

#  music_playlist:
#    name: Playlist
#    options:
#    - Din치mica
#    - M치s reproducidas
#    - M치s valoradas
#    - Modernas (>2000)
#    - Modernas (>2006)
#    - Mazinger
#    initial: Din치mica
#    icon: mdi:library-music

group: !include group.yaml

#zwave:
#  usb_path: /dev/zwave

automation: !include automation.yaml
