default_config:

homeassistant:
  name: Home
  unit_system: metric
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: !secret home_time_zone
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named integrations
