homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret homeassistant_time_zone
  customize: !include customize.yaml

  # Packages
  packages:
    homeassistant: !include packages/homeassistant.yaml
    ipaddress: !include packages/ipaddress.yaml
    datetime: !include packages/datetime.yaml
    mqtt: !include packages/mqtt.yaml
    sip_call: !include packages/sip_call.yaml
    presence: !include packages/presence.yaml
    geo: !include packages/geo.yaml
    security: !include packages/security.yaml
    climate: !include packages/climate.yaml
    power: !include packages/power.yaml
    cameras: !include packages/cameras.yaml
    weather: !include packages/weather.yaml
    #workingdays: !include packages/workingdays.yaml
    #calendars: !include packages/calendars.yaml
    mediaplayer: !include packages/mediaplayer.yaml
    #squeezebox_alert: !include packages/squeezebox_alert.yaml
    kids: !include packages/kids.yaml
    fitness: !include packages/fitness.yaml
    #floorplan: !include packages/floorplan.yaml

http:
  #base_url: 192.168.101.13:8123
#  api_password: !secret http_api_password
#  ssl_certificate: /config/fullchain.pem
#  ssl_key: /config/privkey.pem
  #use_x_forwarded_for: True
  #trusted_networks:
  #  - 127.0.0.1
  #  - ::1
  #  - 192.168.101.0/24

# Enables the frontend
frontend:
# Enables the configration UI
config:
# Enable sun tracking
sun:

zwave:
  usb_path: /dev/ttyACM0

emulated_hue:
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - light
    - media_player

alexa:
  # flash_briefings:
  #   whoishome:
  #     - title: Who's at home?
  #       text: >
  #         {%- if is_state('device_tracker.paulus', 'home') and
  #                is_state('device_tracker.anne_therese', 'home') -%}
  #           You are both home, you silly
  #         {%- else -%}
  #           Anne Therese is at {{ states("device_tracker.anne_therese") }}
  #           and Paulus is at {{ states("device_tracker.paulus") }}
  #         {% endif %}

zone 1:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  radius: 300
  icon: mdi:home

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:
#   include:
#     domains:
#       - sensor
#       - switch
#       - media_player
   exclude:
     entities:
      - sensor.date

# Enables notifications
notify:
  - platform: joaoapps_join
    api_key: !secret join_api_key
    device_id: !secret join_device_id
    device_ids: !secret join_device_ids
    device_names: ZUK Z1
    name: join
  - name: all
    platform: group
    services:
      - service: join
      - service: notify

joaoapps_join:
  - name: android
    device_id: group.android
    api_key: !secret join_api_key

recorder:
  purge_interval: 1
  purge_keep_days: 31

weblink:
  entities:
    - name: Router
      url: https://192.168.101.1
    - name: Rancher
      url: http://192.168.101.13:8080
    - name: Logitech Squeezebox Server
      url: http://192.168.101.13:9000
    - name: ZoneMinder
      url: http://192.168.101.13:8083/zm
    - name: Alarm Keypad
      url: https://192.168.101.17/keypad/

# View all events in a logbook
logbook:

#  - platform: torque
#    email: !secret torque_email
sensor:
  - platform: template
    sensors:
      marty_battery:
        value_template: '{{ states.device_tracker.martyszuk1_z1.attributes.battery }}'
        friendly_name: Marty's Phone Battery
        unit_of_measurement: '%'
  - platform: ups
    name: ups_deliveries
    username: !secret ups_username
    password: !secret ups_password

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

tts:
  - platform: google
    language: 'en'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
  #- platform: yandextts
    #api_key: !secret yandextts_api_key
    #codec: wav
    #voice: oksana
    #emotion: evil
    #speed: 2
  #- platform: picotts
  #platform: voicerss
  #api_key: !secret voicerss_api_key

#input_select:

#  music_playlist:
#    name: Playlist
#    options:
#    - Din치mica
#    - M치s reproducidas
#    - M치s valoradas
#    - Modernas (>2000)
#    - Modernas (>2006)
#    - Mazinger
#    initial: Din치mica
#    icon: mdi:library-music

group: !include group.yaml

automation: !include automation.yaml


#panel_custom:
#  - name: floorplan
#    sidebar_title: Floorplan
#    sidebar_icon: mdi:home
#    url_path: floorplan
#     config: !include packages/floorplan.yaml

logger:
  default: notset

zeroconf:
ios:

  # Example configuration.yaml entry
intent_script:
  GetTemperature:  # Intent type
    speech:
      text: We have {{ states.sensor.temperature }} degrees
    action:
      service: notify.all
      data_template:
        message: Hello from an intent!
