default_config:

homeassistant:
  packages: !include_dir_named integrations

group: !include group.yaml



# zone 1:
#   name: Home
#   latitude: !secret home_latitude
#   longitude: !secret home_longitude
#   radius: 300
#   icon: mdi:home

# zone 2:
#   name: Innovapost
#   latitude: !secret innovapost_latitude
#   longitude: !secret innovapost_longitude
#   radius: 300
#   icon: mdi:email

# zone 3:
#   name: Nav Canada
#   latitude: !secret navcanada_latitude
#   longitude: !secret navcanada_longitude
#   radius: 300
#   icon: mdi:office-building

# zone 4:
#   name: Nav Canada TSC
#   latitude: !secret navcanadatsc_latitude
#   longitude: !secret navcanadatsc_longitude
#   radius: 300
#   icon: mdi:airport

# zone 5:
#   name: Fitness Lab
#   latitude: !secret fitness_lab_latitude
#   longitude: !secret fitness_lab_longitue
#   radius: 300
#   icon: mdi:run-fast

recorder:
  purge_interval: 1
  purge_keep_days: 31

cloud:
  alexa:
    filter:
      exclude_domains:
        - script
        - automation
        - group
