binary_sensor:
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Floorplan

group:
  zones:
    name: Zones
    entities:
      - binary_sensor.floorplan

homeassistant:
  customize:
    binary_sensor.floorplan:
      custom_ui_state_card: floorplan
      floorplan_image: floorplan/floorplan.svg
      entities:
        - binary_sensor.fp_first_garage
        - binary_sensor.fp_first_living_room
        - binary_sensor.fp_first_kitchen
        - binary_sensor.fp_first_family_room
        - binary_sensor.fp_first_hallway
