resources:
  - type: module
    url: /community_plugin/light-entity-row/light-entity-row.js
  - type: module
    url: /community_plugin/dual-gauge-card/dual-gauge-card.js
  - type: module
    url: /community_plugin/gauge-card/gauge-card.js
  - type: module
    url: /community_plugin/compact-custom-header/compact-custom-header.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
title: Home
views:
  - badges: []
    cards:
      - entities:
          - entity: light.aeon_labs_dsc27103_micro_dimmer_2nd_edition_level
            type: 'custom:light-entity-row'
          - entity: light.aeon_labs_zw111_nano_dimmer_level
            type: 'custom:light-entity-row'
          - entity: light.aeon_labs_zw111_nano_dimmer_level_2
            type: 'custom:light-entity-row'
          - entity: light.leviton_dzpd3_2bw_decora_300w_plug_in_smart_dimmer_level
            type: 'custom:light-entity-row'
          - entity: light.garage_ceiling_light
            type: 'custom:light-entity-row'
        title: Lights
        type: entities
      - cards:
          - entities:
              - sensor.speedtest_download
            font_size: 75
            line_color: var(--primary-color)
            line_width: 8
            name: Download
            type: 'custom:mini-graph-card'
            upper_bound: 30
          - entities:
              - sensor.speedtest_upload
            font_size: 75
            line_color: var(--primary-color)
            line_width: 8
            name: Upload
            type: 'custom:mini-graph-card'
            upper_bound: 5
          - entities:
              - sensor.speedtest_ping
            font_size: 75
            line_color: var(--primary-text-color)
            line_width: 8
            name: Ping
            type: 'custom:mini-graph-card'
        type: horizontal-stack
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - entities:
                  - entity: sensor.hallway_thermostat_temperature
                    name: Hallway
                  - entity: sensor.basement_airthings_wave_temperature
                    name: Basement
                font_size: 75
                line_color:
                  - var(--primary-color)
                  - var(--primary-text-color)
                line_width: 8
                name: Temperature
                type: 'custom:mini-graph-card'
              - entities:
                  - entity: sensor.hallway_thermostat_humidity
                    name: Hallway
                  - entity: sensor.basement_airthings_wave_humidity
                    name: Basement
                font_size: 75
                line_color:
                  - var(--primary-color)
                  - var(--primary-text-color)
                line_width: 8
                name: Humidity
                type: 'custom:mini-graph-card'
          - type: horizontal-stack
            cards:
              - entities:
                  - sensor.zooz_zen15_power_switch_power
                font_size: 75
                line_color: var(--primary-color)
                line_width: 8
                name: Dehumidifier Power
                type: 'custom:mini-graph-card'
              - entities:
                  - sensor.basement_airthings_wave_humidity
                font_size: 75
                line_color: var(--primary-text-color)
                line_width: 8
                name: Basement Humidity
                type: 'custom:mini-graph-card'
          - type: horizontal-stack
            cards:
              - entities:
                  - sensor.basement_airthings_wave_radon_1_day_average
                font_size: 75
                line_color: var(--primary-color)
                line_width: 8
                lower_bound: 50
                name: Radon 1 Day Avg.
                type: 'custom:mini-graph-card'
                upper_bound: 150
              - entities:
                  - sensor.basement_airthings_wave_radon_long_term_average
                font_size: 75
                line_color: var(--primary-text-color)
                line_width: 8
                lower_bound: 50
                name: Raydon Long Term Avg.
                type: 'custom:mini-graph-card'
                upper_bound: 150
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.hallway
          - type: weather-forecast
            entity: weather.home
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: input_boolean.guests_home
            show_header_toggle: false
          - entity: alarm_control_panel.alarm_panel
            type: alarm-panel
    panel: false
    path: default_view
    title: Home
  - badges: []
    cards:
      - entity: media_player.spotify
        type: media-control
      - entity: media_player.master_bedroom_tv
        type: media-control
      - entity: media_player.family_room_tv
        type: media-control
    path: media
    title: Media
