resources:
  - type: module
    url: /community_plugin/light-entity-row/light-entity-row.js
  - type: module
    url: /community_plugin/dual-gauge-card/dual-gauge-card.js
  - type: module
    url: /community_plugin/gauge-card/gauge-card.js
  - type: module
    url: /community_plugin/compact-custom-header/compact-custom-header.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
title: Home
views:
  - badges: []
    cards:
      - entity: weather.home
        type: weather-forecast
      - type: horizontal-stack
        cards:
          - type: 'custom:mini-graph-card'
            name: Temperature
            entities:
              - entity: sensor.hallway_thermostat_temperature
                name: Hallway
              - entity: sensor.basement_airthings_wave_temperature
                name: Basement
            line_color:
              - var(--primary-color)
              - var(--primary-text-color)
            line_width: 8
            font_size: 75
          - type: 'custom:mini-graph-card'
            name: Humidity
            entities:
              - entity: sensor.hallway_thermostat_humidity
                name: Hallway
              - entity: sensor.basement_airthings_wave_humidity
                name: Basement
            line_color:
              - var(--primary-color)
              - var(--primary-text-color)
            line_width: 8
            font_size: 75
      - entity: climate.hallway
        type: thermostat
      - entity: alarm_control_panel.alarm_panel
        type: alarm-panel
      - type: horizontal-stack
        cards:
          - type: 'custom:mini-graph-card'
            name: Dehumidifier Power
            entities:
              - sensor.zooz_zen15_power_switch_power
            line_color: var(--primary-color)
            line_width: 8
            font_size: 75
          - type: 'custom:mini-graph-card'
            name: Basement Humidity
            entities:
              - sensor.basement_airthings_wave_humidity
            line_color: var(--primary-text-color)
            line_width: 8
            font_size: 75
      - type: horizontal-stack
        cards:
          - type: 'custom:mini-graph-card'
            name: Radon 1 Day Avg.
            upper_bound: 150
            lower_bound: 50
            line_color: var(--primary-color)
            line_width: 8
            font_size: 75
            entities:
              - sensor.basement_airthings_wave_radon_1_day_average
          - type: 'custom:mini-graph-card'
            name: Raydon Long Term Avg.
            upper_bound: 150
            lower_bound: 50
            line_color: var(--primary-text-color)
            line_width: 8
            font_size: 75
            entities:
              - sensor.basement_airthings_wave_radon_long_term_average
      - entity: media_player.family_room_tv
        type: media-control
      - type: horizontal-stack
        cards:
          - type: 'custom:mini-graph-card'
            name: Download
            upper_bound: 30
            entities:
              - sensor.speedtest_download
            line_color: var(--primary-color)
            line_width: 8
            font_size: 75
          - type: 'custom:mini-graph-card'
            name: Upload
            upper_bound: 5
            entities:
              - sensor.speedtest_upload
            line_color: var(--primary-color)
            line_width: 8
            font_size: 75
          - type: 'custom:mini-graph-card'
            name: Ping
            entities:
              - sensor.speedtest_ping
            line_color: var(--primary-text-color)
            line_width: 8
            font_size: 75
      - entities:
          - entity: light.aeon_labs_dsc27103_micro_dimmer_2nd_edition_level
            type: 'custom:light-entity-row'
          - entity: light.aeon_labs_zw111_nano_dimmer_level
            type: 'custom:light-entity-row'
          - entity: light.aeon_labs_zw111_nano_dimmer_level_2
            type: 'custom:light-entity-row'
          - entity: light.leviton_dzpd3_2bw_decora_300w_plug_in_smart_dimmer_level
            type: 'custom:light-entity-row'
          - entity: light.garage_ceiling_light
            type: 'custom:light-entity-row'
        title: Lights
        type: entities
      - entity: media_player.master_bedroom_tv
        type: media-control
    panel: false
    path: default_view
    title: Home
