cch:
  clock_am_pm: false
  clock_date: true
  clock_format: '24'
  hide_help: true
  voice: clock
custom_header:
  compact_mode: true
  hide_help: true
title: Home
views:
  - badges: []
    cards:
      - cards:
          - card: null
            double_tap_action:
              action: call-service
              service: alarm_control_panel.alarm_disarm
              service_data:
                code: 0528
                entity_id: alarm_control_panel.alarm_panel
            entity: alarm_control_panel.alarm_panel
            hold_action:
              action: call-service
              service: alarm_control_panel.alarm_arm_away
              service_data:
                code: 0528
                entity_id: alarm_control_panel.alarm_panel
            icon: 'mdi:shield-home'
            name: Security System
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              service: alarm_control_panel.alarm_arm_home
              service_data:
                code: 0528
                entity_id: alarm_control_panel.alarm_panel
            theme: default
            type: entity-button
          - card: null
            cards:
              - card:
                  show_state: true
                  type: glance
                filter:
                  include:
                    - domain: person
                    - entity_id: device_tracker.occupants
                type: 'custom:auto-entities'
              - entities:
                  - entity: input_boolean.guests_home
                    name: Guest(s)
                  - entity: input_boolean.vacation_mode
                    name: Vacation
                show_header_toggle: false
                type: entities
            type: horizontal-stack
          - card: null
            cards:
              - aspect_ratio: '1'
                cards: null
                default_zoom: 17
                entities:
                  - entity: person.marty_tremblay
                type: map
              - aspect_ratio: '1'
                cards: null
                default_zoom: 17
                entities:
                  - entity: person.viktoria
                type: map
            type: horizontal-stack
        type: vertical-stack
      - entities:
          - entity: light.aeon_labs_dsc27103_micro_dimmer_2nd_edition_level
            hideColorTemp: true
            type: 'custom:light-entity-row'
          - entity: light.aeon_labs_zw111_nano_dimmer_level
            hideColorTemp: true
            type: 'custom:light-entity-row'
          - entity: light.aeon_labs_zw111_nano_dimmer_level_2
            hideColorTemp: true
            type: 'custom:light-entity-row'
          - entity: light.leviton_dzpd3_2bw_decora_300w_plug_in_smart_dimmer_level
            hideColorTemp: true
            type: 'custom:light-entity-row'
          - entity: light.garage_ceiling_light
            hideColorTemp: true
            type: 'custom:light-entity-row'
        title: Lights
        type: entities
      - cards:
          - cards:
              - color_thresholds:
                  - color: var(--error-color)
                    value: 12
                  - color: var(--primary-text-color)
                    value: 20
                  - color: var(--primary-color)
                    value: 22
                  - color: var(--error-color)
                    value: 24
                entities:
                  - entity: sensor.98_07_2d_4a_97_5c_temperature
                    index: 0
                    name: Basement Temp
                font_size: 75
                line_width: 8
                name: Basement
                type: 'custom:mini-graph-card'
              - color_thresholds:
                  - color: var(--error-color)
                    value: 20
                  - color: var(--primary-text-color)
                    value: 30
                  - color: var(--primary-color)
                    value: 50
                  - color: var(--error-color)
                    value: 55
                entities:
                  - entity: sensor.98_07_2d_4a_97_5c_humidity
                    index: 0
                    name: Basement Humidity
                font_size: 75
                line_width: 8
                name: Basement Humidity
                type: 'custom:mini-graph-card'
            type: horizontal-stack
          - cards:
              - entities:
                  - entity: sensor.zooz_zen15_power_switch_power
                    index: 0
                font_size: 75
                line_color: var(--primary-color)
                line_width: 4
                name: Dehumidifier Power
                type: 'custom:mini-graph-card'
            type: horizontal-stack
          - cards:
              - color_thresholds:
                  - color: var(--primary-color)
                    value: 99
                  - color: var(--error-color)
                    value: 100
                entities:
                  - entity: sensor.98_07_2d_4a_97_5c_radon_1day_avg
                    index: 0
                font_size: 75
                line_width: 8
                lower_bound: 0
                name: Radon 1 Day Avg.
                type: 'custom:mini-graph-card'
                upper_bound: 150
              - color_thresholds:
                  - color: var(--primary-color)
                    value: 99
                  - color: var(--error-color)
                    value: 100
                entities:
                  - entity: sensor.98_07_2d_4a_97_5c_radon_longterm_avg
                    index: 0
                font_size: 75
                line_width: 8
                lower_bound: 0
                name: Raydon Long Term Avg.
                type: 'custom:mini-graph-card'
                upper_bound: 150
            type: horizontal-stack
        type: vertical-stack
      - cards:
          - entities:
              - entity: sensor.speedtest_download
                index: 0
            font_size: 75
            line_color: var(--primary-color)
            line_width: 8
            name: Download
            type: 'custom:mini-graph-card'
            upper_bound: 80
          - entities:
              - entity: sensor.speedtest_upload
                index: 0
            font_size: 75
            line_color: var(--primary-color)
            line_width: 8
            name: Upload
            type: 'custom:mini-graph-card'
            upper_bound: 12
          - entities:
              - entity: sensor.speedtest_ping
                index: 0
            font_size: 75
            line_color: var(--primary-text-color)
            line_width: 8
            name: Ping
            type: 'custom:mini-graph-card'
        type: horizontal-stack
      - cards:
          - entity: weather.home
            type: weather-forecast
        type: vertical-stack
      - card:
          show_state: true
          type: glance
        filter:
          include:
            - entity_id: sensor.gas_price_*
        type: 'custom:auto-entities'
      - aspect_ratio: 50%
        camera_image: camera.cam1
        camera_view: live
        entity: camera.cam1
        image: 'https://www.home-assistant.io/images/merchandise/shirt-frontpage.png'
        name: Front Door
        show_state: false
        type: picture-entity
    icon: 'mdi:home'
    panel: false
    path: default_view
    title: Home
  - badges: []
    cards:
      - entity: media_player.master_bedroom_tv
        type: media-control
      - entity: media_player.family_room_tv
        type: media-control
      - entity: media_player.spotify_retro_hunter
        type: media-control
    icon: 'mdi:music'
    path: media
    title: Media
  - badges: []
    cards:
      - aspect_ratio: 50%
        camera_image: camera.cam1
        camera_view: live
        entity: camera.cam1
        image: 'https://www.home-assistant.io/images/merchandise/shirt-frontpage.png'
        name: Front Door
        type: picture-entity
      - aspect_ratio: 50%
        camera_view: live
        entity: camera.cam2
        image: 'https://www.home-assistant.io/images/merchandise/shirt-frontpage.png'
        name: BBQ
        type: picture-entity
    icon: 'mdi:cctv'
    path: camera
    title: Camera
  - badges: []
    cards:
      - cards:
          - card: null
            double_tap_action:
              action: call-service
              service: alarm_control_panel.alarm_disarm
              service_data:
                code: 0528
                entity_id: alarm_control_panel.alarm_panel
            entity: alarm_control_panel.alarm_panel
            hold_action:
              action: call-service
              service: alarm_control_panel.alarm_arm_away
              service_data:
                code: 0528
                entity_id: alarm_control_panel.alarm_panel
            icon: 'mdi:shield-home'
            name: Security System
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              service: alarm_control_panel.alarm_arm_home
              service_data:
                code: 0528
                entity_id: alarm_control_panel.alarm_panel
            theme: default
            type: entity-button
          - card: null
            cards:
              - card:
                  show_state: true
                  type: glance
                filter:
                  include:
                    - domain: person
                    - entity_id: device_tracker.occupants
                type: 'custom:auto-entities'
              - entities:
                  - entity: input_boolean.guests_home
                    name: Guest(s)
                  - entity: input_boolean.vacation_mode
                    name: Vacation
                show_header_toggle: false
                type: entities
            type: horizontal-stack
          - entity: alarm_control_panel.alarm_panel
            type: alarm-panel
          - card:
              show_state: false
              type: glance
            filter:
              include:
                - entity_id: binary_sensor.motion_*
                - entity_id: binary_sensor.door_*
                - entity_id: binary_sensor.pump*
                - entity_id: binary_sensor.smoke*
            type: 'custom:auto-entities'
        type: vertical-stack
    icon: 'mdi:shield'
    path: security
    title: Security
  - badges: []
    cards:
      - entities:
          - sensor.hl_l5200dw_black_toner_remaining
          - sensor.hl_l5200dw_drum_remaining_life
          - sensor.hl_l5200dw_fuser_remaining_life
          - sensor.hl_l5200dw_laser_remaining_life
          - sensor.hl_l5200dw_page_counter
          - sensor.hl_l5200dw_pf_kit_1_remaining_life
          - sensor.hl_l5200dw_pf_kit_mp_remaining_life
          - sensor.hl_l5200dw_status
          - sensor.hl_l5200dw_uptime
        title: Brother Printer
        type: entities
      - entities:
          - entity: sensor.canada_coronavirus_confirmed
          - entity: sensor.canada_coronavirus_current
          - entity: sensor.canada_coronavirus_deaths
          - entity: sensor.canada_coronavirus_recovered
        title: COVID-19
        type: entities
      - entities:
          - entity: sensor.cyberpower_1500_status_data
          - entity: sensor.cyberpower_1500_battery_charge
          - entity: sensor.cyberpower_1500_load
          - entity: sensor.cyberpower_1500_battery_runtime
          - entity: sensor.cyberpower_1500_input_voltage
        title: CyberPower 1500 UPS
        type: entities
      - entities:
          - entity: sensor.tripp_lite_smart1500rt1u_status_data
          - entity: sensor.tripp_lite_smart1500rt1u_input_voltage
        title: Tripp Lite Smart UPS
        type: entities
    icon: 'mdi:check-network'
    path: environmental
    title: Environmental
