automation:
  - alias: turn on desk light at sunset
    trigger:
      platform: sun
      # Possible values: sunset, sunrise
      event: sunset
    condition:
      - condition: state
        entity_id: 'group.family'
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.desk_light_level

  - alias: turn on desk light at sunset
    trigger:
      platform: time
      at: '23:32:10'
    condition:
      - condition: state
        entity_id: 'group.family'
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.desk_light_level
