zoneminder:
  host: 192.168.101.13:8083

switch:
  - platform: zoneminder
    command_on: Modect
    command_off: Monitor

camera:
  - platform: zoneminder

# image_processing:
#   - platform: seven_segments
#     digits: 2
#     #x_position: 40
#     #y_position: 20
#     height: 160
#     width: 128
#     threshold: 87
#     extra_arguments: "-d 2 -b black"
#     source:
#       - entity_id: camera.camdehumidifier

# android_ip_webcam:
#   name: cam-back-window2
#   host: 192.168.101.88
#   sensors:
#     - battery_level
#     - battery_temp
#     - battery_voltage
#   switches:
#     - night_vision

sensor:
  - platform: zoneminder
    include_archived: true

automation:
  - alias: 'Set night_vision off when sun rises'
    trigger:
        platform: sun
        event: 'sunrise'
        offset: '-00:15:00'
    action:
      - service: switch.turn_off
        entity_id: switch.cambackwindow2_night_vision
  - alias: 'Set night_vision on when sun sets'
    trigger:
        platform: sun
        event: 'sunset'
        offset: '+00:30:00'
    action:
        - service: switch.turn_on
          entity_id: switch.cambackwindow2_night_vision
