# ZoneMinder CCTV
#zoneminder:
#  host: 192.168.101.12:8083

#switch:
#  - platform: zoneminder
#    command_on: Modect
#    command_off: Monitor

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.101.58:8080/live
#  - platform: zoneminder


#sensor:
#  - platform: zoneminder
#    include_archived: true

#android_ip_webcam:
  # This should be the ip of your phone
#  - host: 192.168.101.88
#    name: cam-back-window2

automation:
  - alias: 'Set night_vision off when sun rises'
    trigger:
        platform: sun
        event: sunrise
        offset: '+00:00:00'
    action:
      - service: switch.turn_off
        entity_id: switch.cambackwindow2_night_vision

  - alias: 'Set night_vision on when sun sets'
    trigger:
        platform: sun
        event: sunset
        offset: '+00:00:00'
    action:
        - service: switch.turn_on
          entity_id: switch.cambackwindow2_night_vision
