# Datetime HASS Module
#
# Provides Climate info

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  platform: nest

sensor:
  - platform: nest
    monitored_conditions:
      - 'temperature'
      - 'target'
      - 'humidity'
      - 'operation_mode'
  # - platform: template
  #   sensors:
  #     basement_humidity:
  #       value_template: '{{ states("image_processing.sevensegement_ocr_camdehumidifier") }}'
  #       friendly_name: 'Basement Humidity'
  #       unit_of_measurement: '%'

binary_sensor:
  - platform: nest
    monitored_conditions:
      - 'fan'
      - 'hvac_ac_state'
      - 'hvac_heater_state'
      - 'hvac_aux_heater_state'
      - 'hvac_heat_x2_state'
      - 'hvac_heat_x3_state'
      - 'hvac_alt_heat_state'
      - 'hvac_alt_heat_x2_state'
      - 'hvac_emer_heat_state'
      - 'online'

automation:
  - alias: Nest is back online
    trigger:
      platform: state
      entity_id: binary_sensor.hallway_thermostat_online
      from: 'off'
      to: 'on'
    action:
      service: notify.all
      data_template:
        title: "Nest is back Online!"
        message: "Nest is back Online!"
        data:
          icon: "https://goo.gl/xeetdy"

  - alias: Nest is not online
    trigger:
      platform: state
      entity_id: binary_sensor.hallway_thermostat_online
      from: 'on'
      to: 'off'
    action:
      service: notify.all
      data_template:
        title: "Nest Offline!"
        message: "Nest Offline!"
        data:
          icon: "https://goo.gl/xeetdy"

  # - alias: Basement Dehumidifier offline
  #   trigger:
  #     - platform: state
  #       entity_id: image_processing.sevensegement_ocr_camdehumidifier
  #       to: 'unknown'
  #       for:
  #         minutes: 1
  #   action:
        # service: notify.all
        # data_template:
        #   title: "The basement dehumidifier is offline!"
        #   message: "The basement dehumidifier is offline!"
        #   data:
        #     icon: "https://goo.gl/xeetdy"
