sensor:
  - platform: fedex
    name: Fedex Deliveries
    username: !secret fedex_username
    password: !secret fedex_password

  - platform: ups
    name: UPS Deliveries
    username: !secret ups_username
    password: !secret ups_password
