# Geo HASS Module
#
# Provides several geotracking capabilities.

# Calculate distance to home
proximity:
  m_home:
    devices:
      - device_tracker.martyszuk1_z1
    zone: home
    tolerance: 50
    unit_of_measurement: km

sensor:
  # Statistics of distance to home
  - platform: statistics
    name: Distance to Home
    entity_id: proximity.m_home

  # Serveral travel distances (from Google)
  - platform: google_travel_time
    api_key: !secret google_travel_time_api_key
    name: Home - Work
    origin: !secret google_travel_time_home
    destination: !secret google_travel_time_work

  - platform: google_travel_time
    api_key: !secret google_travel_time_api_key
    name: Work - Home
    origin: !secret google_travel_time_work
    destination: !secret google_travel_time_home
