automation:
  - alias: Time for kids to leave for the bus
    trigger:
      platform: time
      at: '08:12:00'
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      - service: media_player.turn_off
        data:
          entity_id: media_player.family_room_tv
