sensor:
  - platform: plex
    host: 192.168.101.13

media_player:
  - platform: samsungtv
    name: Family Room TV
    host: 192.168.101.155
    mac: 0c:89:10:79:57:63

  # - platform: roku
  #   name: Master Beadroom TV
  #   host: 192.168.101.135

  - platform: plex
    name: Plex Server
    host: 192.168.101.13

  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_secret
