sensor:
  - platform: plex
    host: 192.168.101.12

media_player:
  - platform: samsungtv
    name: Livingroom TV
    host: 192.168.101.155
    mac: 0c:89:10:79:57:63

  - platform: roku
    name: Master Beadroom TV
    host: 192.168.101.135

  - platform: plex
    name: Plex Server
    host: 192.168.101.12

  - platform: squeezebox
    name: Logitech Media Server
    host: 192.168.101.12
    port: 9000

  - platform: gstreamer
    name: 'TTS'
    pipeline: 'audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapcast_tts'

input_select:
  music_playlist:
    name: Playlist
    options:
    - Din치mica
    - M치s reproducidas
    - M치s valoradas
    - Modernas (>2000)
    - Modernas (>2006)
    - Mazinger
    initial: Din치mica
    icon: mdi:library-music
