apcupsd:
  host: 192.168.101.13
  port: 3551

sensor:
  - platform: apcupsd
    resources:
      - status
      - linev
      - loadpct
      - bcharge
      - timeleft

binary_sensor:
  - platform: apcupsd

automation:
  - alias: Mains power is back online
    trigger:
      platform: state
      entity_id: binary_sensor.ups_online_status
      from: 'off'
      to: 'on'
    action:
      service: notify.all
      data_template:
        title: "Mains Power is back Online!"
        message: "Mains Power is back Online!"
        data:
          icon: "https://goo.gl/xeetdy"

  - alias: Mains power is down
    trigger:
      platform: state
      entity_id: binary_sensor.ups_online_status
      from: 'on'
      to: 'off'
    action:
      service: notify.all
      data_template:
        title: "Mains Power is Down!"
        message: "Mains Power is Down!"
        data:
          icon: "https://goo.gl/xeetdy"


  - alias: UPS battery power is low
    trigger:
      platform: numeric_state
      entity_id: sensor.ups_time_left
      below: 5
    action:
      service: notify.all
      data_template:
        title: "UPS battery power is low!"
        message: "UPS battery power is low!"
        data:
          icon: "https://goo.gl/xeetdy"
