input_boolean:
  martyhome:
    name: Marty Home
    initial: on
    icon: mdi:cellphone-android
  viktoriahome:
    name: Viktoria Home
    initial: on
    icon: mdi:cellphone-iphone

device_tracker:
  - platform: google_maps
    username: !secret google_maps_username
    password: !secret google_maps_password
    track_new_devices: true
  - platform: unifi_direct
    host: 192.168.101.3
    username: !secret unifi_username
    password: !secret unifi_password

automation:
  # Presence Detection and Logic
  - alias: 'Marty Away'
    condition:
      condition: state
      entity_id: input_boolean.martyhome
      state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.martysnokia7_wifi
        to: 'not_home'
        for:
          minutes: 10
      - platform: state
        entity_id: device_tracker.martysnokia7
        to: 'not_home'
        for:
          minutes: 10
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.martyhome
      - service: media_player.alexa_tts
        data_template:
          entity_id: "media_player.kitchen"
          message: "Marty has left home"
      - service: logbook.log
        data_template:
          name: "Marty away: "
          message: >-
            {%- for state in states.device_tracker if state.entity_id == trigger.entity_id -%}
              {{ state.attributes.friendly_name }} is Away.
            {%- endfor -%}

  - alias: 'Marty Home'
    condition:
      condition: state
      entity_id: input_boolean.martyhome
      state: 'off'
    trigger:
      - platform: state
        entity_id: device_tracker.martysnokia7, device_tracker.martysnokia7_wifi
        to: 'home'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.martyhome
      - service: media_player.alexa_tts
        data_template:
          entity_id: "media_player.kitchen"
          message: "Marty has arrived home"
      - service: logbook.log
        data_template:
          name: "Marty home: "
          message: >-
            {%- for state in states.device_tracker if state.entity_id == trigger.entity_id -%}
              {{ state.attributes.friendly_name }} is Home.
            {%- endfor -%}

  # ------- Vitoria --------
  - alias: 'Viktoria Away'
    condition:
      condition: state
      entity_id: input_boolean.viktoriahome
      state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.iphone
        to: 'not_home'
        for:
          minutes: 10
      - platform: state
        entity_id: device_tracker.iphone_2
        to: 'not_home'
        for:
          minutes: 10
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.viktoriahome
      - service: media_player.alexa_tts
        data_template:
          entity_id: "media_player.kitchen"
          message: "Viktoria has left home"
      - service: logbook.log
        data_template:
          name: "Viktoria away: "
          message: >-
            {%- for state in states.device_tracker if state.entity_id == trigger.entity_id -%}
              {{ state.attributes.friendly_name }} is Away.
            {%- endfor -%}

  - alias: 'Viktoria Home'
    condition:
      condition: state
      entity_id: input_boolean.viktoriahome
      state: 'off'
    trigger:
      - platform: state
        entity_id: device_tracker.iphone, device_tracker.iphone_2
        to: 'home'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.viktoriahome
      - service: media_player.alexa_tts
        data_template:
          entity_id: "media_player.kitchen"
          message: "Viktoria has arrived home"
      - service: logbook.log
        data_template:
          name: "Viktoria home: "
          message: >-
            {%- for state in states.device_tracker if state.entity_id == trigger.entity_id -%}
              {{ state.attributes.friendly_name }} is Home.
            {%- endfor -%}
