input_boolean:
  martyhome:
    name: Marty Home
    initial: on
    icon: mdi:cellphone-android
  viktoriahome:
    name: Viktoria Home
    initial: on
    icon: mdi:cellphone-iphone

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
  - platform: unifi
    host: 192.168.101.12
    port: 8443
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false

automation:
  # Presence Detection and Logic
  - alias: 'Marty Away'
    condition:
      condition: state
      entity_id: input_boolean.martyhome
      state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.androidbf1392b7f2ba2bce
        to: 'not_home'
        for:
          minutes: 10
      - platform: state
        entity_id: device_tracker.martyszuk1_z1
        to: 'not_home'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.martyhome
      - service: logbook.log
        data_template:
          name: "Marty away: "
          message: >-
            {%- for state in states.device_tracker if state.entity_id == trigger.entity_id -%}
              {{ state.attributes.friendly_name }} is Away.
            {%- endfor -%}

  - alias: 'Marty Home'
    condition:
      condition: state
      entity_id: input_boolean.martyhome
      state: 'off'
    trigger:
      - platform: state
        entity_id: device_tracker.martyszuk1_z1, device_tracker.androidbf1392b7f2ba2bce
        to: 'home'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.martyhome
      - service: logbook.log
        data_template:
          name: "Marty home: "
          message: >-
            {%- for state in states.device_tracker if state.entity_id == trigger.entity_id -%}
              {{ state.attributes.friendly_name }} is Home.
            {%- endfor -%}

  # ------- Vitoria --------
  - alias: 'Viktoria Away'
    condition:
      condition: state
      entity_id: input_boolean.viktoriahome
      state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.viktoriasiphone
        to: 'not_home'
        for:
          minutes: 10
      - platform: state
        entity_id: device_tracker.viktoriaiphone_vt
        to: 'not_home'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.viktoriahome
      - service: logbook.log
        data_template:
          name: "Viktoria away: "
          message: >-
            {%- for state in states.device_tracker if state.entity_id == trigger.entity_id -%}
              {{ state.attributes.friendly_name }} is Away.
            {%- endfor -%}

  - alias: 'Viktoria Home'
    condition:
      condition: state
      entity_id: input_boolean.viktoriahome
      state: 'off'
    trigger:
      - platform: state
        entity_id: device_tracker.viktoriasiphone, device_tracker.viktoriaiphone_vt
        to: 'home'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.viktoriahome
      - service: logbook.log
        data_template:
          name: "Viktoria home: "
          message: >-
            {%- for state in states.device_tracker if state.entity_id == trigger.entity_id -%}
              {{ state.attributes.friendly_name }} is Home.
            {%- endfor -%}
