sensor:
  - platform: rest
    scan_interval: 3600
    resource: !secret gasbuddy_resource_m
    method: GET
    name: Gas Price M
    value_template: '{{value_json.fuels[0].prices[0].price}}'
    unit_of_measurement: '$/lit'
  - platform: rest
    scan_interval: 3600
    resource: !secret gasbuddy_resource_k
    method: GET
    name: Gas Price K
    value_template: '{{value_json.fuels[0].prices[0].price}}'
    unit_of_measurement: '$/lit'
  - platform: rest
    scan_interval: 3600
    resource: http://lcboapi.com/stores/699/products/492207/inventory
    method: GET
    name: lcbo
    value_template: '{{value_json.result.quantity}}'
    unit_of_measurement: 'bottles'
