binary_sensor:

  - platform: template
    sensors:
      working_day:
        value_template: '{{ not now().isoweekday() in (6,7) }}'
        friendly_name: 'Weekend'
        entity_id: sensor.time

  - platform: template
    sensors:
      quiet_time:
        value_template: '{{ ( (states.sensor.working_day.state == "on" and (now().hour < 9 or now().hour >= 22)) or (now().hour < 10) ) }}'
        friendly_name: 'Weeknight'
        entity_id: sensor.time
